### ISSUE TITLE
Uncaught error and compareTo issue

### ISSUE THREAD

**Issue by misterch0c** [irlnathan/activityoverlord20#3]
Firstly thanks a lot for this. I've followed the video and I have 2 little issues.
`Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.12/$injector/modulerr?p0=SignupModule&p1=Er…p%3A%2F    %2Flocalhost%3A1337%2Fjs%2Fdependencies%2Fangular.min.js%3A17%3A431)` 
The error link redirects me to [this page](https://docs.angularjs.org/error/$injector/modulerr?p0=SignupModule&p1=Error:%20%5B$injector:modulerr%5D%20http:%2F%2Ferrors.angularjs.org%2F1.2.12%2F$injector%2Fmodulerr%3Fp0%3DcompareTo%26p1%3DError%253A%2520%255B%2524injector%253Aunpr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.2.12%252F%2524injector%252Funpr%253Fp0%253D%252524compileProvider%250A%2520%2520%2520%2520at%2520Error%2520%28native%29%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A1337%252Fjs%252Fdependencies%252Fangular.min.js%253A6%253A450%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A1337%252Fjs%252Fdependencies%252Fangular.min.js%253A32%253A125%250A%2520%2520%2520%2520at%2520Object.c%2520%255Bas%2520get%255D%2520%28http%253A%252F%252Flocalhost%253A1337%252Fjs%252Fdependencies%252Fangular.min.js%253A30%253A200%29%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A1337%252Fjs%252Fdependencies%252Fangular.min.js%253A29%253A284%250A%2520%2520%2520%2520at%2520Array.forEach%2520%28native%29%250A%2520%2520%2520%2520at%2520q%2520%28http%253A%252F%252Flocalhost%253A1337%252Fjs%252Fdependencies%252Fangular.min.js%253A7%253A280%29%250A%2520%2520%2520%2520at%2520e%2520%28http%253A%252F%252Flocalhost%253A1337%252Fjs%252Fdependencies%252Fangular.min.js%253A29%253A115%29%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A1337%252Fjs%252Fdependencies%252Fangular.min.js%253A29%253A192%250A%2520%2520%2520%2520at%2520Array.forEach%2520%28native%29%0A%20%20%20%20at%20Error%20%28native%29%0A%20%20%20%20at%20http:%2F%2Flocalhost:1337%2Fjs%2Fdependencies%2Fangular.min.js:6:450%0A%20%20%20%20at%20http:%2F%2Flocalhost:1337%2Fjs%2Fdependencies%2Fangular.min.js:30:1%0A%20%20%20%20at%20Array.forEach%20%28native%29%0A%20%20%20%20at%20q%20%28http:%2F%2Flocalhost:1337%2Fjs%2Fdependencies%2Fangular.min.js:7:280%29%0A%20%20%20%20at%20e%20%28http:%2F%2Flocalhost:1337%2Fjs%2Fdependencies%2Fangular.min.js:29:115%29%0A%20%20%20%20at%20http:%2F%2Flocalhost:1337%2Fjs%2Fdependencies%2Fangular.min.js:29:192%0A%20%20%20%20at%20Array.forEach%20%28native%29%0A%20%20%20%20at%20q%20%28http:%2F%2Flocalhost:1337%2Fjs%2Fdependencies%2Fangular.min.js:7:280%29%0A%20%20%20%20at%20e%20%28http:%2F%2Flocalhost:1337%2Fjs%2Fdependencies%2Fangular.min.js:29:115%29) so I included ngRoute but error is still here.
The page allo says:

> This error can also occur if you have tried to add your own components to the ng module. This has never been supported and from 1.3.0 it will actually trigger this error. For instance the following code could trigger this error.
> angular.module('ng').filter('tel', function (){});

So maybe it's just the wrong way to do it? 

I got previous error and one thing that I had to do and was not coverd in the video angular.min.js etc At the end I have this:

```
    <script src="/js/dependencies/sails.io.js"></script>
    <script src="/js/dependencies/angular1.3.js"></script>
    <script src="/js/dependencies/angular.min.js"></script>
    <script src="/js/dependencies/angular-route.js"></script>
    <script src="/js/dependencies/angular-route.min.js"></script>
    <script src="/js/dependencies/angular-toastr.js"></script>
    <script src="/js/dependencies/compareTo.module.js"></script>
    <script src="/js/public/signup/SignupModule.js"></script>
    <script src="/js/public/signup/SignupController.js"></script>

```

So there's that error but it doesn't seem to cause any problem, I just want to get rid of it..

Second issue is that everything is not in the middle of the screen like in your video. Probably a boostrap issue I guess, so everything is stretched, how do I make it fixed size?
edit: this second issue is solved using the same bootstrap file as the one in the repos.

edit with a third issue: when I specify the compareTo module like at the end of the video I get
TypeError: Cannot set property 'compareTo' of undefined. But this is probably linked to the first issue since the module doesn't seem to load properly

Hope you'll make ep4 soon = D thx

**Comment by irlnathan** [comment]
If you send me a link to your repo I'll take a look.

**Comment by crislar** [comment]
Taking the opportunity to give a big Thumbs up to the activityoverlord20!

thanks Christian

Irl Nathan wrote:

> If you send me a link to your repo I'll take a look.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/irlnathan/activityoverlord20/issues/3#issuecomment-75869234.

## 

Christian de Larrinaga

## FBCS, CITP, MCMA

## @ FirstHand

+44 7989 386778

## cdel@firsthand.net

**Comment by misterch0c** [comment]
well seems the issue is always me, I resolved all those problems at the end of the day. Thank you though
